<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Description>Control's Library for Avalonia.</Description>	  
		<PackageIcon>AuraUILogo_full_icon.png</PackageIcon>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<Nullable>enable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<None Include="AuraUILogo_full_icon.png" Pack="true" PackagePath="\" />
	</ItemGroup>
	<ItemGroup>
   
		<AvaloniaResource Include="**\*.xaml">
			<SubType>Designer</SubType>
		</AvaloniaResource>
	  <AvaloniaResource Include="Assets\squares.png" />
	</ItemGroup>
	<Import Project="..\..\build\version.props" />
	<ItemGroup>
	  <PackageReference Include="AuraUtilities" Version="0.1.5.5" />
	  <PackageReference Include="Avalonia" Version="12.0.1" />
	  <PackageReference Include="Avalonia.Desktop" Version="12.0.1" />
	  <PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="12.0.1" />
	  <PackageReference Include="ReactiveUI" Version="23.2.1" />
	  <PackageReference Include="ReactiveUI.Avalonia" Version="12.0.1" />
	  <PackageReference Include="System.Reactive" Version="6.1.0" />
	  <PackageReference Include="System.Text.Json" Version="10.0.7" />
	</ItemGroup>
</Project>
